apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels: 
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mongo
  template:
    metadata:
      labels:
          app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: secret-db
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret-db
              key: password
---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb-svc
spec:
  selector: 
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
