apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-x-deploy
  labels: 
    app: mongo-x
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mongo-x
  template:
    metadata:
      labels:
        app: mongo-x
    spec:
      containers:
      - name: mongo-x
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            secretKeyRef:
              name: secret-db
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret-db
              key: password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata: 
  name: mongo-x-service
spec:
  selector: 
    app: mongo-x
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000
